// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxktwwUavb1hBSSNRlE5DGSNmQh8JPaQ',
    appId: '1:870289477717:android:568a5abadb6916414f04dc',
    messagingSenderId: '870289477717',
    projectId: 'flutter-coding-test-4a3e4',
    storageBucket: 'flutter-coding-test-4a3e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXTdqPVKg3j1lzeLLC41iKhMAf5_aNks',
    appId: '1:870289477717:ios:4b6b4c85302dd65b4f04dc',
    messagingSenderId: '870289477717',
    projectId: 'flutter-coding-test-4a3e4',
    storageBucket: 'flutter-coding-test-4a3e4.appspot.com',
    androidClientId: '870289477717-htdrk01rcha5eq0dn7uc4fd2lfl1jr23.apps.googleusercontent.com',
    iosClientId: '870289477717-hud04mabfo06l2me9f9g49t6kqhdsf7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiTrackerApp',
  );
}
